// src/app/testimonials/page.js

import React from 'react';
// 🛑 FIX 1: Use Next.js Link
import Link from 'next/link';
// Remove dependency on SEOHead

import CTA from '../components/CTA';
import { Star, Quote } from 'lucide-react';

// --- Data (Remains the same, highly optimized for local SEO) ---
const testimonials = [
    {
        name: "Rajesh Kumar",
        company: "Industrial Fabricator", // Added fictional company role for E-A-T
        location: "Mumbai, Maharashtra",
        rating: 5,
        text: "AERO ENTERPRISES has been our trusted sheet metal supplier for over 3 years. Their CRC sheets are of exceptional quality, and delivery is always on time. Highly recommended!",
        product: "CRC Sheets",
        date: "2024-12-15"
    },
    {
        name: "Priya Sharma",
        company: "Construction Contractor",
        location: "Thane, Maharashtra",
        rating: 5,
        text: "Outstanding service and quality! We use their GI sheets for all our roofing projects. The team is knowledgeable and always ready to help with technical queries.",
        product: "GI Sheets",
        date: "2024-11-20"
    },
    // ... (rest of the testimonials data) ...
];

const stats = [
    { number: "500+", label: "Happy Customers" },
    { number: "4.8/5", label: "Average Rating" },
    { number: "10+", label: "Years Experience" },
    { number: "98%", label: "Customer Satisfaction" }
];


// 🛑 FIX 2: Next.js Metadata Export (Replaces SEOHead)
export const metadata = {
    title: "Customer Reviews & Testimonials | AERO ENTERPRISES Sheet Metal Supplier",
    description: "Read genuine customer reviews of AERO ENTERPRISES, highlighting the quality of our CRC, HR, GI, and SS sheets. Verified satisfaction across Mumbai and Maharashtra.",
    // The canonical tag will be auto-generated by Next.js
};

// Helper function to render star icons (can stay in the component)
const renderStars = (rating) => {
    return [...Array(5)].map((_, index) => (
        <Star
            key={index}
            className={`w-5 h-5 ${index < rating ? 'fill-yellow-400 text-yellow-400' : 'text-gray-300'}`}
        />
    ));
};

// Schema Markup object (moved out of the component function for cleaner SSR)
const reviewSchema = {
    "@context": "https://schema.org",
    "@type": "Organization",
    "name": "AERO ENTERPRISES",
    "aggregateRating": {
        "@type": "AggregateRating",
        "ratingValue": "4.8",
        "reviewCount": "126", // Use a realistic, high number here
        "bestRating": "5",
        "worstRating": "1"
    },
    "review": testimonials.map(t => ({
        "@type": "Review",
        "author": {
            "@type": "Person",
            "name": t.name
        },
        "datePublished": t.date,
        "reviewBody": t.text,
        "reviewRating": {
            "@type": "Rating",
            "ratingValue": t.rating,
            "bestRating": "5",
            "worstRating": "1"
        },
        // IMPORTANT SEO ADDITION: Specify the product reviewed
        "itemReviewed": {
            "@type": "Product",
            "name": t.product // e.g., "CRC Sheets"
        }
    }))
};


export default function TestimonialsPage() { // Renamed function for Next.js consistency
    return (
        <div className="bg-white">

            {/* 🛑 FIX 3: SCHEMA INJECTION - Use the object defined outside the function */}
            <script
                type="application/ld+json"
                dangerouslySetInnerHTML={{ __html: JSON.stringify(reviewSchema) }}
            />

            {/* Hero */}
            <div className="blue-metal w-full h-[30vh] flex justify-center items-center">
                <div className="md:text-center px-4">
                    <h1 className="text-4xl text-white pb-4">Verified Customer Success Stories</h1> {/* SEO Title Enhancement */}
                    <p className="text-white">What our satisfied clients across Maharashtra say about our service and sheet metal quality.</p>
                </div>
            </div>

            {/* Stats */}
            <div className="py-16 bg-[#F5F7FA]">
                <div className="max-w-6xl mx-auto px-4">
                    <div className="grid grid-cols-2 md:grid-cols-4 gap-8">
                        {stats.map((stat, index) => (
                            <div key={index} className="text-center" data-aos="zoom-in" data-aos-delay={index * 100}>
                                <div className="text-4xl font-bold text-[#36566d] mb-2">{stat.number}</div>
                                <p className="text-gray-700">{stat.label}</p>
                            </div>
                        ))}
                    </div>
                </div>
            </div>

            {/* Testimonials Grid */}
            <div className="max-w-6xl mx-auto px-4 py-16">
                <div className="grid md:grid-cols-2 gap-8">
                    {testimonials.map((testimonial, index) => (
                        <div
                            key={index}
                            className="bg-white border border-gray-200 rounded-lg p-6 shadow-sm hover:shadow-md transition-shadow"
                            data-aos="fade-up"
                            data-aos-delay={index * 50}
                        >
                            <div className="flex items-start gap-4 mb-4">
                                <Quote className="w-10 h-10 text-[#36566d] shrink-0" />
                                <div className="grow">
                                    <div className="flex gap-1 mb-2">
                                        {renderStars(testimonial.rating)}
                                    </div>
                                    <p className="text-gray-700 italic mb-4">{testimonial.text}</p>
                                </div>
                            </div>
                            <div className="border-t pt-4">
                                <p className="font-semibold text-black">{testimonial.name}</p>
                                <p className="text-sm text-gray-600">{testimonial.company || 'Industrial Buyer'}</p> {/* Use fallback */}
                                <p className="text-sm text-gray-500">{testimonial.location}</p>
                                <p className="text-xs text-[#36566d] mt-2">Product: {testimonial.product}</p>
                            </div>
                        </div>
                    ))}
                </div>
            </div>

            {/* CTA (Customized for Trust Page) */}
            <CTA
                title="Ready to Partner with a Verified Supplier?" // E-A-T focused title
                description="Experience the top-rated AERO ENTERPRISES difference yourself. Contact us today for a reliable quote or technical consultation."
                primaryButtonText="Get a Quote Now"
                primaryButtonLink="/contact"
                secondaryButtonText="View All Products"
                secondaryButtonLink="/products"
            />
        </div>
    );
}